// Does the real drumgen Lua run in the browser, and does the page look like a
// drum machine?
//
// This is the go/no-go for the device-free UI, so it asserts the chain end to end
// rather than "the page loaded": the fengari VM boots from a lazy import, the Lua
// sources come from /lua/drumgen (the same files the host tests run), a bar
// generated by gen.lua arrives as data, and ui.lua's pixels reach a canvas.
//
// Needs ng serve on :4211 - it never starts servers (see playwright.config.ts).

import { expect, test } from '@playwright/test';

/** The 128x64 screen is drawn at 4x by default, so this is 512x256. */
const SCREEN = { width: 512, height: 256 };

/** Bars played so far, read off the readout the page shows. */
async function bars(page: import('@playwright/test').Page): Promise<number> {
  const text = (await page.locator('.panel-head .mono').textContent()) ?? '';
  return parseInt(/(\d+) bars/.exec(text)?.[1] ?? '0', 10);
}

test.describe('drumgen in-browser lua', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/drumgen');
    await expect(page.locator('.status')).toContainText('real lua is running', {
      timeout: 30_000,
    });
  });

  test('runs the real gen.lua and returns a bar', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(String(e)));

    await expect(page.locator('.status .dot')).toHaveClass(/ok/);

    // every served lua file is listed with its hash, so drift is visible
    const files = page.locator('.files .file');
    await expect(files).toHaveCount(8);
    for (const name of ['gen.lua', 'bridge.lua', 'ui.lua', 'screen.lua', 'font6x8.lua']) {
      await expect(page.locator('.files .file', { hasText: name })).toBeVisible();
    }

    // events crossed the bridge with resolved note numbers
    const events = await page.evaluate(() =>
      Array.from(document.querySelectorAll('.readout dd')).map((d) => d.textContent),
    );
    expect(events.length).toBeGreaterThan(0);

    // the readout reports the real kit notes
    const kit = events[events.length - 1] ?? '';
    expect(kit).toMatch(/36 38/);

    expect(errors).toEqual([]);
  });

  test('paints the pixels ui.lua drew', async ({ page }) => {
    const canvas = page.locator('canvas.screen');
    await expect(canvas).toBeVisible();

    const size = await canvas.evaluate((el) => ({
      width: (el as HTMLCanvasElement).width,
      height: (el as HTMLCanvasElement).height,
    }));
    // 128x64 at the default 4x: the screen must keep its 2:1 aspect
    expect(size.width / size.height).toBeCloseTo(SCREEN.width / SCREEN.height, 2);

    // not a blank canvas: some pixel is lit, and the picture has both states
    const levels = await canvas.evaluate((el) => {
      const c = el as HTMLCanvasElement;
      const ctx = c.getContext('2d')!;
      const { data } = ctx.getImageData(0, 0, c.width, c.height);
      const seen = new Set<number>();
      for (let i = 0; i < data.length; i += 4) seen.add(data[i]);
      return Array.from(seen).sort((a, b) => a - b);
    });
    expect(levels.length).toBeGreaterThan(1);
    expect(levels[levels.length - 1]).toBeGreaterThan(0);
  });

  test('the scale buttons resize the screen without breaking the aspect', async ({ page }) => {
    const canvas = page.locator('canvas.screen');
    const width = async () =>
      canvas.evaluate((el) => (el as HTMLCanvasElement).width);

    const at4 = await width();
    await page.locator('.scale', { hasText: '2x' }).click();
    const at2 = await width();
    expect(at2).toBeLessThan(at4);
    expect(at2 / (at4 / 2)).toBeCloseTo(1, 1);
  });

  test('the three keys do what the screen says they do', async ({ page }) => {
    const status = page.locator('.status');

    // key 1 is play/stop. The page is already playing on load, so one press
    // stops it: the bar counter then stops advancing, which is the observable.
    await page.locator('.key', { hasText: 'play / stop' }).click();
    const bar = await status.textContent();
    await page.waitForTimeout(1500);
    expect(await status.textContent()).toBe(bar);

    // key 2 steps the style, and the header names the new one
    await expect(status).toContainText('four_on_floor');
    await page.locator('.key', { hasText: 'next style' }).click();
    await expect(status).not.toContainText('four_on_floor');

    // key 3 is the swing page, which the encoders' labels then say out loud
    await page.locator('.key', { hasText: 'swing page' }).click();
    await expect(page.locator('.knob-note')).toBeVisible();
    await expect(page.locator('.knobs')).toContainText('swing');
  });

  test('the encoders move the params they are labelled with', async ({ page }) => {
    const first = page.locator('.knob', { hasText: 'E1' });
    const value = async () => (await first.locator('span').first().textContent()) ?? '';
    const before = parseInt(await value(), 10);

    await first.locator('.dial').click();
    await expect
      .poll(async () => parseInt(await value(), 10))
      .toBeGreaterThan(before);

    // and back down, which proves the label is bound to the param it names
    await first.locator('.dial').click({ button: 'right' });
    await expect.poll(async () => parseInt(await value(), 10)).toBe(before);
  });

  test('plays by itself, so nothing has to be clicked to hear it', async ({ page }) => {
    const first = await bars(page);
    // 120bpm is a two second bar; wait for the clock, not for a click
    await expect.poll(() => bars(page), { timeout: 15_000 }).toBeGreaterThan(first + 1);
  });

  test('PLAY stops the clock, and PLAY again starts it', async ({ page }) => {
    // The clock is a host timer and `playing` is Lua state, so this is the test
    // that they agree: a button that flips the flag without stopping the timer
    // looks fine for one bar and then plays on forever.
    const play = page.locator('.key', { hasText: 'play / stop' });
    await expect.poll(() => bars(page), { timeout: 15_000 }).toBeGreaterThan(0);

    await play.click();
    // A stop can land after the bar in flight was already queued, so settle first
    // and only then take the reading that has to stay still.
    await page.waitForTimeout(2500);
    const stopped = await bars(page);
    await page.waitForTimeout(5000);
    expect(await bars(page)).toBe(stopped);

    await play.click();
    await expect.poll(() => bars(page), { timeout: 15_000 }).toBeGreaterThan(stopped);
  });
});