// Does the real drumgen Lua actually run in the browser?
//
// This is the go/no-go for the whole device-free UI plan, so it asserts the
// chain end to end rather than just "the page loaded": the fengari VM boots from
// a lazy import, the Lua sources come from /lua/drumgen (the same files the host
// tests run), and a bar generated by monome/drumgen/lib/gen.lua arrives as data.
// What is asserted here is the editable grid (rows), not the generated bar.
//
// Needs ng serve on :4211 - it never starts servers (see playwright.config.ts).

import { expect, test } from '@playwright/test';

test.describe('drumgen in-browser lua', () => {
  test('runs the real gen.lua and returns a bar', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(String(e)));

    await page.goto('/drumgen');

    // status flips to the success text only after boot() came back ok:true
    await expect(page.locator('.status')).toContainText('real lua is running', {
      timeout: 30_000,
    });
    await expect(page.locator('.status .dot')).toHaveClass(/ok/);

    // the served lua files are listed with their hashes, so drift is visible
    await expect(page.locator('.files .file')).toHaveCount(5);
    await expect(page.locator('.files .file', { hasText: 'gen.lua' })).toBeVisible();

    // a generated bar: kick on every beat, so lane 1 has hits on steps 1 and 5
    const rows = await page.evaluate(() => {
      const text = document.querySelector('.grid')?.textContent ?? '';
      return text.split('\n').map((line) => line.split(' '));
    });
    expect(rows).toHaveLength(10); // ten kit voices, one row each
    expect(rows[0]).toHaveLength(16); // sixteen steps
    expect(rows[0][0]).not.toBe('.'); // kick on step 1
    expect(rows[0][4]).not.toBe('.'); // and on step 5

    // events crossed the bridge with resolved note numbers
    await expect(page.locator('.panel-head')).toContainText('events in this bar');

    expect(errors).toEqual([]);
  });

  test('a second bar is a different bar', async ({ page }) => {
    await page.goto('/drumgen');
    await expect(page.locator('.status')).toContainText('real lua is running', {
      timeout: 30_000,
    });
    // the bar counter is the real proof the generator advanced
    await expect(page.locator('.status')).toContainText('bar 1');
    const first = await page.locator('.grid').textContent();
    await page.getByRole('button', { name: 'next bar' }).click();
    await expect(page.locator('.status')).toContainText('bar 2');
    expect(await page.locator('.grid').textContent()).not.toBe(first);
  });
});
